{% set name = "osdatahub" %}
{% set version = "1.2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8b57f2c0ee060f39e83ea117b4393ada082c4eeef9e82c860e9567a7730dfd22

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - geojson ==2.5.0
    - python >=3.7
    - requests ==2.25.0
    - shapely ==1.8.0
    - typeguard ==2.13.0
    - tqdm ~=4.62.3

test:
  imports:
    - osdatahub
    - osdatahub.FeaturesAPI
    - osdatahub.NamesAPI
    - osdatahub.PlacesAPI

about:
  home: https://github.com/OrdnanceSurvey/osdatahub
  license: OGL-UK-3.0
  license_family: OTHER
  license_file: LICENSE.txt
  summary: osdatahub is Ordnance Survey's (OS) Python API wrapper, designed to make data from the OS Data Hub APIs readily accessible to developers.
  doc_url: https://osdatahub.readthedocs.io/en/latest/
  dev_url: https://github.com/OrdnanceSurvey/osdatahub

extra:
  recipe-maintainers:
    - dchirst
    - JEPooleyOS
    - FHunt-OS
