{% set name = "osdatahub" %}
{% set version = "1.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 580feb9456f2feb79bc5158a161799058168d05a0034ab563d108df76c30c120

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=84.0.0
  run:
    - geojson >=3.3.0
    - python >=3.11
    - requests >=2.34.2
    - shapely >=2.1.2
    - typeguard >=4.6.0
    - tqdm >=4.67.1
    - urllib3 >=2.8.0
    - zipp >=4.1.0
    - pytest-asyncio>=1.4.0
    - aiohttp>=3.14.3
test:
  requires:
    - python {{ python_min }}
  imports:
    - osdatahub
    - osdatahub.FeaturesAPI
    - osdatahub.NamesAPI
    - osdatahub.PlacesAPI

about:
  home: https://github.com/OrdnanceSurvey/osdatahub
  license: OGL-UK-3.0
  license_family: OTHER
  license_file: LICENSE.txt
  summary: osdatahub is Ordnance Survey's (OS) Python API wrapper, designed to make data from the OS Data Hub APIs readily accessible to developers.
  doc_url: https://osdatahub.readthedocs.io/en/latest/
  dev_url: https://github.com/OrdnanceSurvey/osdatahub

extra:
  recipe-maintainers:
    - JEPooleyOS
    - FHunt-OS
    - JEPooley
    - jmbraybrook
