{% set name = "osdatahub" %}
{% set version = "1.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e4daa74e31e05b8c3637473e577b419d0153f53635708c756102bcfbde799433

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.10
    - setuptools >=80.9.0
  run:
    - geojson ~=3.2.0
    - python >=3.10
    - requests ~=2.32.4
    - shapely ~=2.1.1
    - typeguard ~=4.4.4
    - tqdm ~=4.67.1
    - urllib3 >=2.5.0
    - zipp >=3.23.0 
test:
  imports:
    - osdatahub
    - osdatahub.FeaturesAPI
    - osdatahub.NamesAPI
    - osdatahub.PlacesAPI

about:
  home: https://github.com/OrdnanceSurvey/osdatahub
  license: OGL-UK-3.0
  license_family: OTHER
  license_file: LICENSE.txt
  summary: osdatahub is Ordnance Survey's (OS) Python API wrapper, designed to make data from the OS Data Hub APIs readily accessible to developers.
  doc_url: https://osdatahub.readthedocs.io/en/latest/
  dev_url: https://github.com/OrdnanceSurvey/osdatahub

extra:
  recipe-maintainers:
    - JEPooleyOS
    - FHunt-OS
    - JEPooley
    - jmbraybrook
