{% set name = "osdatahub" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: aa66d66e1011bf951086a49e98398a48bb4d41abe794fd47dc18fbc0c0659ff7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python 3.8
    - setuptools
  run:
    - geojson ==2.5.0
    - python >=3.8
    - requests ==2.25.0
    - shapely ==1.8.0
    - typeguard ==2.13.0
    - tqdm ~=4.62.3

test:
  imports:
    - osdatahub
    - osdatahub.FeaturesAPI
    - osdatahub.NamesAPI
    - osdatahub.PlacesAPI

about:
  home: https://github.com/OrdnanceSurvey/osdatahub
  license: OGL-UK-3.0
  license_family: OTHER
  license_file: LICENSE.txt
  summary: osdatahub is Ordnance Survey's (OS) Python API wrapper, designed to make data from the OS Data Hub APIs readily accessible to developers.
  doc_url: https://osdatahub.readthedocs.io/en/latest/
  dev_url: https://github.com/OrdnanceSurvey/osdatahub

extra:
  recipe-maintainers:
    - JEPooleyOS
    - FHunt-OS
    - JEPooley
    - jmbraybrook
